version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: "increase"
    open-pull-requests-limit: 10
    directory: "/"
    labels:
      - "dependabot"
    assignees:
      - "nyaarium"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "12:00"
    # automerged_updates:
    #   - match:
    #       dependency_type: "all"
    #       update_type: "semver:patch"
    #   - match:
    #       dependency_type: "all"
    #       update_type: "semver:minor"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"

      nextjs:
        patterns:
          - "next"
          - "eslint-config-next"

      remix:
        patterns:
          - "@remix-run/*"

      material-ui:
        patterns:
          - "@mui/material"
          - "@mui/icons-material"

      emotion:
        patterns:
          - "@emotion/*"

      mikro-orm:
        patterns:
          - "@mikro-orm/*"

      eslint:
        patterns:
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
