services:
  app:
    depends_on:
      - postgres-dev
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.compose
    volumes:
      - ./volume/data:/data

  postgres-dev:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nyaakube
    volumes:
      - ./volumes/data:/data
      - ./volumes/db:/var/lib/postgresql/data
