name: Workflow Call - Dependency Review

on:
  workflow_call:

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: "moderate"
          deny-licenses: LGPL-2.0, BSD-2-Clause
