name: Workflow Call - Dependency Review

on:
  workflow_call:

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: "moderate"
          deny-licenses: |
            GPL-2.0
            GPL-3.0
            LGPL-2.0
            LGPL-2.1
            LGPL-3.0
            AGPL-3.0
            SSPL-1.0
            CAL-1.0
            CATOSL-1.1
            BUSL-1.1
            CDDL-1.0
            CDDL-1.1
            MS-PL
