name: Trigger Dependabot Check

on:
  workflow_call:

  workflow_dispatch:

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger Dependabot
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"event_type": "dependabot_trigger"}' \
          https://api.github.com/repos/${{ github.repository }}/dispatches
