name: Renovate
on:
  schedule:
    - cron: "0 10 * * 1" # Runs every Monday at 10:00 AM
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Renovate
        uses: renovatebot/github-action@v40.2.4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          configurationFile: .github/renovate-config.js
