name: Renovate
on:
  workflow_dispatch:

  schedule:
    - cron: "0 11 * * *" # Run every day at 11:00 UTC (3:00 AM PST)

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Renovate
        uses: renovatebot/github-action@v40.2.4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          configurationFile: .github/renovate-config.js
