name: Renovate
on:
  workflow_dispatch:

  schedule:
    # Run 3 times a day every day starting 10:15 UTC (3:15 AM PST)
    - cron: "15 10 * * *"
    - cron: "30 10 * * *"
    - cron: "45 10 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Renovate
        uses: renovatebot/github-action@v40.2.6
        with:
          token: ${{ secrets.PAT_TOKEN }}
          configurationFile: .github/renovate-config.js
