# Uses secrets:
#   WEBSITE_URL

name: ZAP Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1"

jobs:
  zap:
    name: ZAP Scanner
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: "${{ secrets.WEBSITE_URL }}"
          allow_issue_writing: false
          cmd_options:
            # Use Ajax spider for modern websites
            "-j"
