# Uses secrets:
#   WEBSITE_URL           - Web address of the site
#   ZAP_AUTH_HEADER_VALUE - Secret value to inform your server this attack is authorized

name: ZAP Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1"

jobs:
  zap:
    name: ZAP Scanner
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    env:
      ZAP_AUTH_HEADER_VALUE: ${{ secrets.ZAP_AUTH_HEADER_VALUE }}
      ZAP_AUTH_HEADER_SITE: ${{ secrets.WEBSITE_URL }}
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: "${{ secrets.WEBSITE_URL }}"
          allow_issue_writing: false
          cmd_options:
            # Use Ajax spider for modern websites
            "-j"
